### ISSUE TITLE
Hey ive tried the open sourse files but i keep getting the error: while running  cargo run --release

### ISSUE THREAD

**Issue by Amal-Baby-Mathews** [pixelspark/poly#1]
Finished release [optimized] target(s) in 0.77s
     Running `target\release\llmd.exe`
2023-11-16T09:54:21.455840Z  INFO llmd: Starting llmd; bind address: 0.0.0.0:3000
2023-11-16T09:54:21.473117Z  INFO poly_backend::backend: backend instantiating metal=false cache_path="C:\\Users\\seq_amal\\AppData\\Local\\Dialogic\\Poly\\cache"
thread 'tokio-runtime-worker' panicked at C:\Users\seq_amal\poly-open-sourced\poly-open-sourced\poly-backend\src\backend.rs:139:22:
load model: InvalidMagic { path: "./data/gpt2-small-dutch-f16.bin", magic: 73726576 (vers) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at C:\Users\seq_amal\poly-open-sourced\poly-open-sourced\poly-backend\src\backend.rs:143:14:
     Running `target\release\llmd.exe`
2023-11-16T09:56:39.715217Z  INFO llmd: Starting llmd; bind address: 0.0.0.0:3000       
2023-11-16T09:56:39.719853Z  INFO poly_backend::backend: backend instantiating metal=false cache_path="C:\\Users\\seq_amal\\AppData\\Local\\Dialogic\\Poly\\cache"
thread 'tokio-runtime-worker' panicked at C:\Users\seq_amal\poly-open-sourced\poly-open-sourced\poly-backend\src\backend.rs:139:22:
load model: InvalidMagic { path: "./data/gpt2-small-dutch-f16.bin", magic: 73726576 (verse cache_path="C:\\Users\\seq_amal\\AppData\\Local\\Dialogic\\Poly\\cache"s) }                                                                                    sourced\poly-backend\src\backend.rs:139:22:
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace           s) }
thread 'main' panicked at C:\Users\seq_amal\poly-open-sourced\poly-open-sourced\poly-backend\src\backend.rs:143:14:                                                             kend\src\backend.rs:143:14:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(6), ...)
error: process didn't exit successfully: `target\release\llmd.exe` (exit code: 101)

**Comment by pixelspark** [comment]
Please run `git lfs checkout` and ensure it downloads the model files from LFS. Otherwise it will try to read the LFS pointer files, which obviously won't work.
