### ISSUE TITLE
memories.text not working 

### ISSUE THREAD

**Issue by Amal-Baby-Mathews** [pixelspark/poly#3]
@pixelspark Thank you for clearing all the previous issues. I'll provide my config.toml to my poly_ui directory as i am first trying to run the app locally: 
[models.gpt2]
model_path = "./data/gpt2.bin"
architecture = "gpt2"
use_gpu = false

[memories.test]
store_prompts = true 
embedding_model = "./data/orcamini3b"
dimensions = 3200
store = { hora = { path = "test.index" } }
chunk_separators = ["."]
chunk_max_tokens = 255

[tasks.dutch_completion]
model = "gpt2"
prelude = "### System:\nChat with the user\n"
prefix =  "\n### User:\n"
postfix = "\n### Response:"
samplers = ["mirostat1:n_vocab=32000"]
memorization = { memory = "test", retrieve = 2 }

The terminal keeps encountering the error: `Result::unwrap()` on an `Err` value: Error { inner: Error { inner: TomlError { message: "missing field `store_prompts`"

Am i doing something wrog or should i change something in the directory i have installed all the models and used the accurate paths for the same

**Comment by pixelspark** [comment]
@Amal-Baby-Mathews I am sorry but the Issues section is not intended for individual user support, only for (reproducible!) defects in the software and feature requests. Just set `store_prompts` to either true or false - look through the code to see what it does (i.e. https://github.com/search?q=repo%3Apixelspark%2Fpoly%20store_prompts&type=code). 

PRs to improve documentation are of course welcome.
